version: "3.9"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "mysql" ]
      timeout: 20s
      retries: 10
    restart: on-failure

  mysql-startup-command:
    image: mysql:5.7
    platform: linux/x86_64
    links:
      - "mysql:mysql"
    volumes:
      - ./scripts:/scripts
    command: >
      /bin/sh /scripts/mysql-setup-script.sh
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  app:
    build: .
    command: go run main.go
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=post_db
      - DB_HOST=mysql
      - DB_DRIVER=mysql
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: on-failure